### ISSUE TITLE
Add jest and write at least one test

### ISSUE THREAD

**Issue by ameerthehacker** [ameerthehacker/named-avatar-generator#4]
## Description

* Add jest as dev dependency
* Add npm script to run the test
* Write at least one test to test a function whichever is easy for you

**Comment by NoahvdAa** [comment]
I will pick this up.

**Comment by ameerthehacker** [comment]
cool please goahed

**Comment by itsadeadh2** [comment]
Can I still do one? I mean, I didnt know I was supposed to comment here that I was doing it...

**Comment by NoahvdAa** [comment]
@itsadeadh2 It's fine by me if you do it instead of me.

**Comment by itsadeadh2** [comment]
@NoahvdAa thanks man :smiley_cat:

**Comment by ameerthehacker** [comment]
closing this as a PR has already been made and merged
